name: 'Booking Site'
description: 'A recipe tailored to best practices for kickstarting a new Drupal 10 project.'
type: 'Site'

install:
  - bm
  - select2
  - field_group

config:
  import:
    bm: '*'
  actions:
    gin.settings:
      simple_config_update:
        preset_accent_color: light_blue
        preset_focus_color: green
        classic_toolbar: classic
        layout_density: medium
        sticky_action_buttons: false
